using MediatR;
using Logistics.Domain.Entities;
using Logistics.Infrastructure.Data; // We will abstract this dependency via interfaces later, but let's wire it up simply first

namespace Logistics.Application.Orders.Commands;

// 1. The Command: Data needed to execute the action
public record CreateOrderCommand(string CustomerId, decimal TotalAmount) : IRequest<Guid>;

// 2. The Handler: The actual business use-case logic execution
public class CreateOrderCommandHandler : IRequestHandler<CreateOrderCommand, Guid>
{
    private readonly ApplicationDbContext _context;

    public CreateOrderCommandHandler(ApplicationDbContext context)
    {
        _context = context;
    }

    public async Task<Guid> Handle(CreateOrderCommand request, CancellationToken cancellationToken)
    {
        // Enforce Domain validation rules by executing the domain factory method
        var order = Order.Create(request.CustomerId, request.TotalAmount);

        // Persist to the database infrastructure
        await _context.Orders.AddAsync(order, cancellationToken);
        await _context.SaveChangesAsync(cancellationToken);

        // Return the identifier generated by the Domain
        return order.Id;
    }
}
